### ISSUE TITLE
rowId option unavailable?

### ISSUE THREAD

**Issue by lukemccomb** [ephemer/meteor-reactive-datatables#31]
I'm having trouble utilizing the `rowId` option described here: https://datatables.net/reference/option/rowId
Is this possible with this package?
In my options object for my data table, I have:
```
            scrollY: '400px',
            scrollX: false,
            autoWidth: true,
            responsive: true,
            paging: false,
            bPaginate: false,
            bFilter: true,
            info: true,
            *rowId: 'meritId'*
```
Where the last attribute `rowId` should ideally be adding the unique `meritId` from each record I'm passing in the data according to the DataTables docs. I'm not seeing an ID added to the rows so I was wondering if anyone has a solution for this or could help me troubleshoot.

Thanks for any help!

**Comment by Architecty** [comment]
I was fiddling with this and found the following solution: Instead of putting it into the options, map a field called `DT_RowId` to your data object. Datatables will automatically assign this as the rowID.

For example, in the data function:
`return Documents.find({}).map(function(doc){
doc['DT_RowId'] = doc._id;
return doc;
});`

**Comment by ephemer** [comment]
This looks resolved to me, the philosophy of this package is to not add API if it's at all possible to avoid it. Let me know if Architecty's solution doesn't work for you
