### ISSUE TITLE
Use of Collection in Render Function

### ISSUE THREAD

**Issue by manusharma1** [ephemer/meteor-reactive-datatables#40]
Hi @ephemer 

Could you Please suggest me on how to use Collection in the render function

Below is my code:

	lead_source_manager_data = function () {
	    return LeadSources.find({}, {sort: {order_id: 1}}).fetch();
	};

	function renderEditLeadSources(recordid, renderType, currentRow) {

			// Check if this record has the presence in the Project DB if yes then we cannot delete them as deleteing this record will have affect on the Project Data as this entry has reference there
			
			var countrecordentryinProjects = Projects.find({lead_source:recordid}).count();

			if(countrecordentryinProjects>0){
			
			var deletevar = '';
			
			}else{

			var deletevar = '<a class="btn deleteentry" id="'+recordid+'" data-toggle="confirmation" data-id="'+recordid+'" data-placement="right" data-original-title="" title="">Delete</a>'
			
			}
			
		return deletevar;
	}

	var optionsObjectLeadSources = {
		columns: [{
			title: 'Lead Source Name',
			data: 'lead_source_name', 
		}, {
			title: 'Order',
			data: 'order_id',
		},{
			title: 'Delete',
			data: '_id',
		render: renderEditLeadSources('_id')
		}],
		"order": [[ 1, "asc" ]]
	};

	Template.lead_source_manager.helpers({

	    FetchLeadSources: function () {
		return lead_source_manager_data;
	    },

	    optionsObjectLeadSources: optionsObjectLeadSources
	});

**var countrecordentryinProjects = Projects.find({lead_source:recordid}).count();**

I am getting an error that Projects is undefined

**ReferenceError: Projects is not defined**

Thanks and Best Regards,
Manu

**Comment by manusharma1** [comment]
Hi @ephemer 

I am waiting for your reply, Could you Please give me some hint?

Thanks and Best Regards,
Manu

**Comment by ephemer** [comment]
Hi, this is not an issue with Reactive DataTables. Sorry but it is completely out of my scope to help you with this issue. If Projects is not defined it is because you have not defined it as a collection in your code, or maybe you have not correctly imported it if you are using ES6 modules.

Either way this is an incomplete code example, I recommend you remake what you're trying to do in an example project in the simplest possible way. Please refer to https://medium.com/@dan_abramov/asking-good-questions-421f08ee7e5c#.ey81flsxn for more information about how to do this effectively. I'm going to close this for now because it is not useful to other users of the library.

**Comment by manusharma1** [comment]
Hi @ephemer ,

Thanks for your reply. I have defined Projects this in the common code and all my helpers can access this .The only issue, I am facing that I want to disable delete link in case there are reference of the data in the Projects collection and when I am calling that in the render function it is giving me this issue.

`Projects = new Meteor.Collection('projects');`

Thanks and Best Regards,
Manu

**Comment by ephemer** [comment]
Manu, this is still a bug with your code and not with the package. I can't help you with this, sorry.
